---
title: "ggstreams"
author: "Duncan Gates"
date: "5/8/2021"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, fig.showtext = T, fig.retina = 1)
source(here::here("R/stream_art.R"))
```


```{r}
ggstream2(n_fill = 30, y_range = 1:3, palette = nord_palettes$baie_mouton,
          flip = T)

ggsave(here("Images/cool_stream3.png"), height = 12, width = 8)

knitr::plot_crop(here("Images/cool_stream3.png"))
```


```{r}
ggstream2(n_fill = 10, y_range = 1:1, palette = nord_palettes$lumina,
          flip = T)

ggsave(here("Images/cool_stream4.png"), height = 12, width = 8)

knitr::plot_crop(here("Images/cool_stream4.png"))
```


```{r}
ggstream2(n_fill = 25, y_range = 1:1.75, palette = nord_palettes$afternoon_prarie,
          flip = T)

ggsave(here("Images/cool_stream5.png"), height = 12, width = 8)

knitr::plot_crop(here("Images/cool_stream5.png"))
```


```{r}
source(here::here("R/stream_art.R"))
ggstream2(n_fill = 30, y_range = c(1, 1), palette = nord_palettes$afternoon_prarie,
          flip = T, bw = 0.8, geom = "polygon", size = 0.05, color = "white")
```









```{r}
ggsave(here("Images/cool_stream6.png"), height = 12, width = 8)

knitr::plot_crop(here("Images/cool_stream6.png"))
```

